language: android
jdk:
  - oraclejdk8

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-25.0.1
    - android-25
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'

before_install:
  - echo 'android.builder.sdkDownload=false' > gradle.properties

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &

script:
  - ./gradlew test -PisRelease=false dokka install
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - ./gradlew connectedCheck -PisRelease=false

notifications:
  email: false
