language: android
jdk: oraclejdk7

android:
  components:
  - android-21
  - build-tools-21.1.2

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
 - ./gradlew clean build assemble -s -i
 - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && ./gradlew connectedCheck -s -i || false'

after_success:
 - ./gradlew artifactoryPublish

notifications:
  email: change